= Containers From Scratch
:toc: macro
:toclevels: 4
:doctype: book
:listing-caption: Listing
:sectnumlevels: 6
:numbered:
:chapter-label:
:imagesdir: images/
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::backend-pdf[]
:pygments-style: tango
:source-highlighter: rouge
:rouge-style: github
:autofit-option:
endif::[]

// Create the Table of contents here
toc::[]


I will try to explain through simple examples how *linux namespaces* technology is used to create that thing we call *containers*. I'd also like to mention that most of the content has been taken from many blogs I've read and adapted it. You can check all links at the end of the document in the <<Sources>> section. (special thanks to them for such a wonderful articles).

But what a *container* is?. There are many info in blogs, articles over internet generally speaking about containers, according to that we can said that a *container* is isolated process running on a host. Container runtimes takes advantage over some pretty cool Linux kernel technologies that you might have overheard as namespaces, cgroups, chroots, etc. plus security layers like SELinux or Seccomp.

Container runtime have different approaches, in Docker they'll get their own namespace, meanwhile in CoreOS’ rkt, will be grouped and containers will share namespaces, each of which is called a pod.

We will see how we can leverage these technologies on Linux in order to build and run our own containers, and then we will contrast it against kubernetes / openshift

== Tools
include::content/00_tools.adoc[leveloffset=+3]

== Containers introduction
include::content/01_containers_introduction.adoc[leveloffset=+3]

== Building Base Containers
include::content/02_build_your_images.adoc[leveloffset=+3]

== Podman in action
include::content/03_podman_in_action.adoc[leveloffset=+3]

== Pods vs Linux Namespaces
include::content/04_pods_linux_namespaces.adoc[leveloffset=+3]

== Sources
include::content/99_sources.adoc[leveloffset=+3]


